name: checks

on: [push, pull_request]

jobs:
  checks: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python 
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: flake8 action
        uses: py-actions/flake8@v2
      - name: isort
        uses: isort/isort-action@master
  